Preserve string representation when converting to JSON
vert-x3/vertx-config pull request #127
Opened 2021-03-09 15:15 UTC by tsegismont

When converting from properties to JSON, we should preserve the string representation.

Indeed, users might want to get the value '123456' as a String, and so far we would convert it to Double which led to String value being '123456.0'.

Fixes #124

2021-03-10 09:01 UTC, vietj commented on vertx-config/src/main/java/io/vertx/config/Patterns.java
> +import java.util.regex.Pattern;
we don't need a class for 2 constants

2021-03-10 09:01 UTC, vietj requested changes
minor modif

2021-03-10 09:57 UTC, tsegismont commented on vertx-config/src/main/java/io/vertx/config/Patterns.java
> +import java.util.regex.Pattern;
Done

2021-03-11 15:07 UTC, vietj approved these changes

2021-03-11 15:40 UTC, merged